# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name            = 'Zynamic'
author          = 'Zynamic'
github          = 'wroyca/Zynamic'
description     = 'Dynamic binary rewriting with Zydis.'
favicon         = 'favicon.png'
license         = [ 'GPLv3', 'https://github.com/wroyca/Zynamic/blob/master/LICENSE' ]
navbar          = [ 'files' ]

[warnings]
enabled         = true
undocumented    = true
treat_as_errors = false

[sources]
recursive_paths = [ '../src' ]
patterns        = [ '*.hpp' , '*.cpp' ]
extract_all     = true