# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name            = 'Zynamic'
author          = 'wroyca'
github          = 'wroyca/Zynamic'
favicon         = 'favicon.png'
license         = [ 'GPLv3', 'https://github.com/wroyca/Zynamic/blob/main/LICENSE' ]
navbar          = [ 'files' ]

[sources]
recursive_paths = [ '../src' ]
patterns        = [ '*.hpp' , '*.cpp' ]
extract_all     = true
