on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install -y graphviz
          sudo apt-get install -y doxygen
          sudo apt-get install -y python
          sudo apt-get install -y python3-pip
          sudo pip3 install poxy

      - name: Build
        run: |
          cd docs
          poxy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
